---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Loading and preprocessing the data
```{r read data}

library(ggplot2)
library(tidyverse)

data<- read.csv("activity.csv")

data$date<- as.Date(data$date)

#set file paths
file_path <- paste0(getwd(), "/figures")

```

## What is mean total number of steps taken per day?
```{r histogram of total daily steps}
#add counts of steps to each day
data_count<- data %>%  group_by(date) %>% summarise(total_steps = sum(steps, na.rm = TRUE))

#plot histogram of total number of steps per day
ggplot(data_count, aes(x= date, y= total_steps))+
  geom_bar(stat = "identity")+
  scale_x_date()+
  labs(title = "Total steps per day")

#save the figure
ggsave("Daily steps histogram.pdf", path = file_path)

```  

```{r mean and median steps}
# calculate mean and median of steps taken per day 
data_mean<- data %>%  group_by(date) %>%  summarise(mean = mean(steps, na.rm =  TRUE))

data_median<-data %>% group_by(date) %>%  summarise(median = median(steps, na.rm = TRUE))

#report the mean and median values
data_report<- left_join(data_mean, data_median) %>% print()

```

## What is the average daily activity pattern?
```{r time series plot for daily activity pattern }

#organise data into average steps against time interval
data_interval<- data %>%  group_by(interval) %>% summarise(average_steps = mean(steps, na.rm= TRUE)) 

#Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
ggplot(data_interval, aes(interval, average_steps))+
  geom_line()+
  labs(x = "time intervals(minutes)", y = "Average daily steps", title = "Daily Activity Pattern")

#save the figure
ggsave("Daily activity line graph.pdf", path = file_path)

```


```{r Daily activity question and answer}
#print out question and answer for this segment
cat("Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?")

cat("
Time interval 1705 has the highest average steps across all days.")

```


## Imputing missing values
```{r report mising values}
#Calculate and report the total number of missing values in the dataset
cat(paste0("The total number of missing values in the dataset is ", nrow(data[is.na(data), ])))

```

```{r filling in missing values}
#filling in all of the missing values in the dataset with mean of values for the time interval
data_na<-left_join(data[is.na(data), ], data_interval) %>% select(-steps) 

colnames(data_na)<- c("date", "interval", "steps")

#Create a new dataset that is equal to the original dataset but with the missing data filled in.
data_new<-rbind(data_na, na.omit(data))

```

```{r histogram of total steps with imputed missing valuaes}
#calculate total steps for each day with new dataset
data_new_sum<- data_new %>%  group_by(date) %>% summarise(total_steps = sum(steps))

#Make a histogram of the total number of steps taken each day. Calculate and report the mean and median total number of steps taken per day.

ggplot(data_new_sum, aes(x= date, y = total_steps))+
  geom_bar(stat = "identity")+
  labs(x= "date", y = "Number of steps", title = "Total number of steps taken per day")

#save the figure
ggsave("Total steps per day histogram.pdf", path = file_path)

```

```{r report mean and median}
#Calculate the mean total number of steps taken per day
data_new_mean<- data_new %>%  group_by(date) %>%  summarise(new_mean = mean(steps)) 

#Calculate the median total number of steps taken per day
data_new_median<- data_new %>%  group_by(date) %>%  summarise(new_median = median(steps)) 

#Report the mean and median of total number of steps taken per day
data_new_report<- left_join(data_new_mean, data_new_median) %>%  print()

```

```{r Missing values question and answer}
#Do these values differ from the estimates from the first part of the assignment? 
data_mean_median<-left_join(data_report, data_new_report) %>% print()

#tidy up the dataset
data_mean_median<- data_mean_median %>%  gather(key = "stats", value = "value", -date)

#Plot a graph to investigate how imputing impacts the mean and median
ggplot(data_mean_median, aes(x= date, y = value))+
  geom_line(aes(color = stats, linetype = stats))+
  scale_color_manual(values = c("purple", "darkred", "darkgreen", "orange"))

#save the figure
ggsave("Impact of imputing line graph.pdf", path = file_path)

#What is the impact of imputing missing data on the estimates of the total daily number of steps?
cat(paste0("Imputing the data decreased the median."))

```
## Are there differences in activity patterns between weekdays and weekends?

```{r differences between weekdays and weekends}
#Create a new factor variable in the dataset with two levels – “weekday” and “weekend”
data_new <- data_new %>% mutate(weekday = weekdays(date)) 

data_new$weekday<-factor(ifelse(data_new$weekday == c("Saturday", "Sunday"), "weekend", "weekday"))

print(head(data_new))

```

```{r plot time series for weekday and weekend activity}
#calculate sum of steps per interval for both weekends and weekdays
 data_new_mean<-aggregate(steps~weekday+interval, data = data_new, mean)

#Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).
ggplot(data_new_mean, aes(interval, steps))+
  geom_line()+
  facet_grid(~weekday)+
  labs(x = "time intervals(minutes)", y = "Average daily steps", title = "Daily Activity Pattern")

#save the figure
ggsave("average steps weekday vs weekendline graph.pdf", path = file_path)

```
